version: '3.8'

services:

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: chn_sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Password12345
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    networks:
      - chn_net

  backend:
    build:
      context: ./BACKEND/demo   
      dockerfile: Dockerfile    
    container_name: chn_backend
    depends_on:
      - sqlserver
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:sqlserver://chn_sqlserver:1433;databaseName=master;encrypt=false
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=Password12345
      - SPRING_JPA_HIBERNATE_DDL_AUTO=none
    networks:
      - chn_net


  frontend:
    build:
      context: ./FRONTEND/frontend
      dockerfile: Dockerfile
    container_name: chn_frontend
    ports:
      - "4200:4200"
    depends_on:
      - backend
    networks:
      - chn_net
volumes:
  sqlserver_data:

networks:
  chn_net:
